---
- hosts: all
  vars: 
    - package: samba
    - service: samba
  tasks:
    - name: Instalar {{ package }} 
      yum:
        name: "{{ package }}"
        state: latest
    - name: Iniciando {{ service }}
      service:
        name: "{{ service }}"
        state: started 
        enabled: true
...
